Ecommerce Backend initial version PR
shubham-ghuge/api-farmers-grocery pull request #1
Opened 2021-05-07 10:28 UTC by shubham-ghuge

Hey, Please review my code.

2021-05-07 17:08 UTC, prithviBytes commented on app.js
> +
Hi Shubham,
Over here could you please add an invalid route handler?
Something like 404 route not found!

2021-05-07 17:17 UTC, prithviBytes commented on db/connect.db.js
> +}
Hey,
Over here you are usingboth async await and promises. Use one of them.
I would suggest you go for async await and surround it with try catch block.

```
try{
     await mongoose.connect()
}catch(err){
  do something
}

2021-05-07 17:19 UTC, prithviBytes requested changes
Hi Shubham,
The code looks good, I have requested 2 changes. Do ping me for further clarifications if needed.
Thanks,
Prithvi

2021-05-08 06:15 UTC, shubham-ghuge commented
> Hi Shubham,
> The code looks good, I have requested 2 changes. Do ping me for further clarifications if needed.
> Thanks,
> Prithvi

Thank you for your time, Prithvi.
I have completed the changes.

2021-05-09 06:16 UTC, prithviBytes approved these changes
Hi Shubham,
Thanks for the changes.
I am approving the PR from my end.

2021-07-02 10:57 UTC, merged